version: "3.8"
services:
  smilecdr:
    container_name: smilecdr-2023.05.R02
    image: smilecdr:2023.05.R02
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
      - "9000:9000"
      - "9100:9100"
      - "9200:9200"
      - "9201:9201"
    volumes:
      - db:/home/smile/smilecdr/database
      - log:/home/smile/smilecdr/log
      - mq:/home/smile/smilecdr/activemq-data
      - tmp:/home/smile/smilecdr/tmp
    restart: "unless-stopped"
volumes:
  db:
  log:
  mq:
  tmp: