services:
  smilecdr:
    container_name: smilecdr
    image: smilecdr:latest
    ports:
      - "8000:8000"
      - "8001:8001"
      - "9000:9000"
      - "9100:9100"
      - "9200:9200"
    volumes:
      - ./runtime/smilecdr_log:/home/smile/smilecdr/log
      - ./runtime/smilecdr_db:/home/smile/smilecdr/database
      - ./runtime/smilecdr_mq:/home/smile/smilecdr/activemq-data
