version: "3.8"
services:
  smilecdr:
    container_name: smilecdr
    image: smilecdr:latest
    ports:
      - "8000:8000"
      - "8001:8001"
      - "9000:9000"
      - "9100:9100"
      - "9200:9200"
      - "9201:9201"
    volumes:
      - log:/home/smile/smilecdr/log
      - db:/home/smile/smilecdr/database
      - mq:/home/smile/smilecdr/activemq-data
      - tmp:/home/smile/smilecdr/tmp
    restart: "unless-stopped "
volumes:
  db:
  log:
  mq:
  tmp:
